### ISSUE TITLE
ERROR_INITIALIZATION_FAILED  : failed vkAcquireNextImageKHR for any examples.

### ISSUE THREAD

**Issue by Andreyogld3d** [pumexx/pumex#3]
Hi, @pumexx 

I try to run some examples:
 
..\Pumex\bin\pumexcrowd.exe
Crowd rendering
Exception thrown : [ c:\dev\pumex\src\pumex\surface.cpp : 308 : ERROR_INITIALIZATION_FAILED ] : failed vkAcquireNextImageKHR

...\Pumex\bin\pumexgpucull.exe
Object culling on GPU
Exception thrown : [ c:\dev\pumex\src\pumex\surface.cpp : 308 : ERROR_INITIALIZATION_FAILED ] : failed vkAcquireNextImageKHR

...\Pumex\bin\pumexmultiview.exe
Multiview deferred rendering with PBR and antialiasing
Exception thrown : [ c:\dev\pumex\src\pumex\surface.cpp : 308 : ERROR_INITIALIZATION_FAILED ] : failed vkAcquireNextImageKHR

...\Pumex\bin\pumexdeferred.exe
Deferred rendering with physically based rendering and antialiasing : depth prepass present, 4 samples per pixel
Exception thrown : [ c:\dev\pumex\src\pumex\surface.cpp : 308 : ERROR_INITIALIZATION_FAILED ] : failed vkAcquireNextImageKHR

GPU info you can find there https://vulkan.gpuinfo.org/displayreport.php?id=3824
The same problem on other GPU R7 240 (Windows 7 X64)

My project with Vulkan can run on these GPU without errors.

I can help you to fix it, but i need to compile your project, can you attach the minimal compiled example ?

**Comment by pumexx** [comment]
Hi @Andreyogld3d,

VK_ERROR_INITIALIZATION_FAILED suggests that problem lies in the driver
( from Vulkan specification : Initialization of an object could not be completed 
for implementation-specific reasons ), or maybe during initialization I used 
some parameters that are not accepted by AMD driver ( just guessing ).

Also the driver looks little bit old : it declares API version 1.0.26.

Unfortunately, I don't have any AMD graphics card and never tested 
Pumex on any such card ( I suspected there will be some problems ).

pumexviewer is minimal compiled example that you are able to run.
It needs a model provided in command line to work, for example :

pumexviewer people/wmale1_lod0.dae

You can also try to run other Pumex examples with Vulkan debug layers turned on.
Maybe layers will be more verbose about possible cause of error :

pumexdeferred -d

Compilation is pretty straightforward and described in README.md : 

https://github.com/pumexx/pumex#building-and-installation-on-windows

All dependencies will be downloaded at first compilation.

**Comment by Andreyogld3d** [comment]
Hi @pumexx, I have compiled example pumexdeferred, but i was fixing some error during compilation/running...
Finally, I have error from Vulkan Debug layers:

ERROR: [Validation] Code 341838338 :  [ VUID-VkSwapchainCreateInfoKHR-presentMode-01281 ] Object: 0x13f3bfc0 (Type = 3) | vkCreateSwapChainKHR() called with a non-supported presentMode (i.e. VK_PRESENT_MODE_MAILBOX_KHR). The spec valid usage text states 'presentMode must be one of the VkPresentModeKHR values returned by vkGetPhysicalDeviceSurfacePresentModesKHR for the surface' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-presentMode-01281)

**Comment by pumexx** [comment]
@Andreyogld3d, could you test if the example works with other 
presentation modes when debug layers are enabled ?

pumexdeferred -d -p immediate
pumexdeferred -d -p fifo
pumexdeferred -d -p fifo_relaxed

All my examples use VK_PRESENT_MODE_MAILBOX_KHR by default.
NVidia driver on Linux does not have this mode implemented, but it informs about it 
and switches to immediate mode. Now I know, that AMD driver lets the application 
crash without trying to switch to other modes.

I will try to do something about it. Maybe I implement picking default presentation mode 
from modes delivered by the driver.

**Comment by Andreyogld3d** [comment]
> All my examples use VK_PRESENT_MODE_MAILBOX_KHR by default.

I think you should use only supported presentation modes for current GPU, vkGetPhysicalDeviceSurfacePresentModesKHR has returned supported modes:
VK_PRESENT_MODE_IMMEDIATE_KHR, VK_PRESENT_MODE_FIFO_KHR.

I have result:

> pumexdeferred -d -p immediate
> pumexdeferred -d -p fifo
> pumexdeferred -d -p fifo_relaxed

Ok:

![image](https://user-images.githubusercontent.com/8597425/44033606-99337ab2-9f13-11e8-8191-cc00bbd1eadd.png)


> Maybe I implement picking default presentation mode from modes delivered by the driver.

Yes, sounds as technical right decision.
Now you can fix this error.

**Comment by pumexx** [comment]
The issue has been resolved ( commit : ab7e47b ).
When user picks presentation mode that is not available, then library will pick available presentation mode that is most similar to user's choice ( in case of AMD cards for example: mailbox mode will be replaced by immediate mode. If user picks fifo_relaxed mode, then library will use fifo mode ).
Appropriate warning information will be sent to log.
