### ISSUE TITLE
Remove unnecessary checks for API handles

### ISSUE THREAD

**Issue by elfring** [pumexx/pumex#4]
[An extra check is not needed for a zero API handle](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#fundamentals-validusage-handles "Do I need to check for null before delete p?") in functions like the following.
* [Image](https://github.com/pumexx/pumex/blob/0d1fbed44be8464c8b75172056ddb9e7ad3bb666/src/pumex/Image.cpp#L98 "Destructor for Image")
* [Sampler::validate](https://github.com/pumexx/pumex/blob/0d1fbed44be8464c8b75172056ddb9e7ad3bb666/src/pumex/Sampler.cpp#L117 "Sampler::validate function")

**Comment by pumexx** [comment]
Resolved ( commit e91aa78 ).

I decided to remove handle check from Image class and few other places.

I left Sampler class untouched for now. 
Checking for VH_NULL_HANDLE in validate() method is currently consistent 
for many classes that manage lifetime of Vulkan objects ( like Sampler, 
FrameBuffer, ImageView and many others ). 

These classes will be reviewed by me in near future and suitable 
changes will be made so that the outlook of these classes is consistent.

Thank you for reminding me about these unnecessary checks :)

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/pumexx/pumex/commit/e91aa78768da60c5cafd58bf2eb7ad1b4427376d "Removing few unnecessary handle checks").

Will any update candidates be adjusted a bit later?

**Comment by pumexx** [comment]
Yes, I am planning code review for different aspects of Pumex library in the near future,
because they need improvement in my opinion. 

These aspects include:
- lifetime of Vulkan objects
- validation of scenegraphs
- rebuilding of command buffers
- secondary command buffers
- Vulkan synchronization
- render workflow compilation

These are my plans to improve code quality.
Plans for new features are listed at the end of README.md file.

Cheers :)
